<a href="https://colab.research.google.com/github/dlmacedo/deep-learning-class/blob/master/notebooks/pytorch/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
-------

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.1139e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.4161e-36]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8021, 0.8698, 0.4986],
        [0.5751, 0.6939, 0.2916],
        [0.6471, 0.2292, 0.1067],
        [0.3185, 0.8746, 0.0482],
        [0.1817, 0.1837, 0.4012]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4886,  1.2353, -0.1806],
        [ 0.1279,  1.1154, -1.0810],
        [ 0.0061, -0.1537,  1.6225],
        [-1.1635, -1.5344,  0.0724],
        [ 1.1107, -1.1913,  1.9297]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])



``torch.Size`` is in fact a tuple, so it supports all tuple operations.

Operations
----------

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4897,  2.1003,  0.1663],
        [ 0.7648,  1.8081, -0.5417],
        [ 0.7309, -0.0757,  2.0144],
        [-1.0931, -1.0554,  0.8654],
        [ 1.6666, -0.6443,  2.3975]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.4897,  2.1003,  0.1663],
        [ 0.7648,  1.8081, -0.5417],
        [ 0.7309, -0.0757,  2.0144],
        [-1.0931, -1.0554,  0.8654],
        [ 1.6666, -0.6443,  2.3975]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4897,  2.1003,  0.1663],
        [ 0.7648,  1.8081, -0.5417],
        [ 0.7309, -0.0757,  2.0144],
        [-1.0931, -1.0554,  0.8654],
        [ 1.6666, -0.6443,  2.3975]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4897,  2.1003,  0.1663],
        [ 0.7648,  1.8081, -0.5417],
        [ 0.7309, -0.0757,  2.0144],
        [-1.0931, -1.0554,  0.8654],
        [ 1.6666, -0.6443,  2.3975]])


Any operation that mutates a tensor in-place is post-fixed with an "_".

For example: ``x.copy_(y)``, ``x.t_()``, will change x.

You can use standard NumPy-like indexing with all bells and whistles!



In [13]:
print(x[:, 1])

tensor([ 1.2353,  1.1154, -0.1537, -1.5344, -1.1913])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.6294])
1.6293681859970093


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing mathematical operations, linear algebra, random numbers, etc., are described [here](http://pytorch.org/docs/torch).

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array:



In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor:

See how changing the np array changed the Torch Tensor automatically



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!